### PR TITLE
Add workflow to create a new local community

### PR DESCRIPTION
**Pull request by dicortazar**
Add detailed information on how to create a new local community.
This includes links to existing ticketing system or the ISC Slack channel.

### CODE REVIEW

**Review by yuhattor — APPROVED** [review]
LGTM:)

@spier and @rrrutledge
If you have any, please leave a comment👀

**Comment by yuhattor** [comment]
@dicortazar thank you for compiling the docs. I'll merge this one at this point!
If any additional modifications are needed, please create a new PR!

**Comment by tfroment** [comment]
Thank you for this documentation. So, it answers my initial questions regarding visio conference tooling. I assume the creation of a (local) youtube channel is in the "other tools" category, so  that any local community can create its own channel, do you confirm?

**Comment by yuhattor** [comment]
I think you can create your channel for posting InnerSource videos for now. But actually, I'm not sure how it should be organized in the future, I think it's odd to have, let's say, 10 InnerSource channel in different languages. 
There may come a time in the future when local communities should be merged into the main channel when it has swelled. (Actually it would be great if that happened!)

**Comment by spier** [comment]
@tfroment @yuhattor great conversation here!

I will just leave one note here if we want to explore this further maybe we should move the conversation to a new issue or similar?

I also think that having each local community create their own YouTube channel is fine for now.
We can consolidate this later, if we find that useful.

We could still do a tiny bit of integration by adding the local channels as "featured channels" to the main account.
I just added the "InnerSource Commons Japan" channel to the main channel in that manner.

What do you think, would that be helpful?

The aforementioned integration would show the "InnerSource Commons Japan" channel in two places on the main channel:

1) On the [home page](https://www.youtube.com/@InnerSourceCommons/featured) of the main channel

Screenshot 2023-02-20 at 22 40 57

2) On the [channels tab](https://www.youtube.com/@InnerSourceCommons/channels) of the main channel

Screenshot 2023-02-20 at 22 37 25

**Comment by tfroment** [comment]
Hi, just initialized the FR Youtube channel : https://www.youtube.com/@innersourcecommonsfrance

**Comment by yuhattor** [comment]
wonderful!!
🚀🚀🚀

**Pull request merged**
